### ISSUE TITLE
The mouse hits screen size limit even if I make it bigger
It does not know where it's going. Really restrictive 
Sometime when bringing it back it takes longer

### ISSUE THREAD

**Issue by Uddhav07** [rohitsangwan01/uni_control_hub#20]

**Comment by Uddhav07** [comment]
mostly the issue depends on how i accelerate my mouse or mouse speed

**Comment by rohitsangwan01** [comment]
@Uddhav07 Released [v0.0.8](https://github.com/rohitsangwan01/uni_control_hub/releases/tag/v0.0.8) today, with the ability to lock mouse within the client using hotkeys, with the help of hotkey, This will not solve the exact issue, because there are few limitations, but atleast provide a better alternative
