### ISSUE TITLE
Can't exit screen (Android + MacOS over USB)

### ISSUE THREAD

**Issue by joepio** [rohitsangwan01/uni_control_hub#32]
**Describe the bug**
Entering the Android screen works fine, but exiting required me to remove the USB port.

**To Reproduce**

1. Connect Android device over USB
2. Move cursor to android device
3. Try to move cursor back to MacOS device
4. Cursor stays there

**Expected behavior**
I expected to be able to leave the Android screen where I entered it (in my case the top)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: Xiaomi Pad 6
 - OS: HarmonyOS latest

**Comment by rohitsangwan01** [comment]
@joepio Thats kind of limitation right now, because once you are connected with android, android will think that a hardware is connected and it will show the cursor, 
We can remove the Cursor when screen left android screen by unregistering the AOA services

But then for android, it will be like we plugin in actual hardware Mouse in android when cursor enters from desktop to Android, and we remove the Mouse when cursor left android
Not sure if this will be a good approach, because few android devices send notification when AOA device registers
so if we keep Registering/Unregistering the AOA service, android will bloat with the notifications of A hardware Mouse or Keyboard is connecting and disconnecting

**Comment by rohitsangwan01** [comment]
If you have any ideas or questions, please feel free to reopen the issue or start a discussion. Your input is always welcome!
